name: 'Java TestNG GitHub Actions Test'
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Update browserstack.yml file'
        run: |
          FILE="browserstack.yml"
          yq -i '.buildName = "Github Actions Build Name"' "$FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add browserstack.yml
          git commit -m "Updated BrowserStack YML config ahead of run"
          git push -u origin main

      - name: 'BrowserStack Environment Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Building web application to be tested'
        run: mvn clean install -D skipTests

      - name: 'Running test on BrowserStack'  # Invokes the actual test script that would run on BrowserStack browsers
        run: mvn clean test -P sample-test  # See sample test script above
